#CAPTCHA, lockout, rate-limiting, TOTP, pepper
#"sha256","bcrypt", "argon2id"
#password level: weak, meduim, strong

attack:
  bruteforce: false
  passwordspraying: true
config:
  hash: "sha256"
  pass_level:
  salt: true
  pepper: true
protection:
  captcha: false
  lockout: true
  rate-limit: false
  TOTP: false
GROUP_SEED: 114467408
  