#CAPTCHA, lockout, rate-limiting, TOTP, pepper
#"sha256","bcrypt", "argon2id"

attack:
  bruteforce:
  passwordspraying: true
config:
  hash: "bcrypt"
  pass_level:
  salt: true
  pepper: false
protection:
  captcha: true
  lockout: false
  rate-limit: false
  TOTP: false
GROUP_SEED: 114467408
  